apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/seabaylea/action.git
              revision: master
          template:
            name: express 
            arguments:
              - name: IMAGE
                value: express-action:latest
      revisionTemplate:
        spec:
          container:
            image: express-action:latest
            imagePullPolicy: IfNotPresent 
